### ISSUE TITLE
Java runtime exception when select the board in Arduino IDE prior to 1.8.x

### ISSUE THREAD

**Issue by board707** [board707/w80x_arduino#5]
The package seems to incompatible with IDE prior to 1.8.13
The error message

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.BaseNoGui.getBoardPreferences(BaseNoGui.java:165)
	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:804)
	at processing.app.Base.onBoardOrPortChange(Base.java:1301)
	at processing.app.Base$12.actionPerformed(Base.java:1524)
	at processing.app.Base.filterVisibilityOfSubsequentBoardMenus(Base.java:1563)
	at processing.app.Base.access$000(Base.java:81)
	at processing.app.Base$11.actionPerformed(Base.java:1496)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
I have no ideas what it mean.

**Comment by AnatolSher** [comment]
What package are you talking about?
I checked the package in your fork in IDE 1.8.19 and 2.0.3. There are no Java runtime errors.
The package I prepared recently contains the new HAL v 0.6.0 and only works under Windows. Look in the discussions

О каком пакете идет речь?
Пакет в Вашем форке я проверял в IDE 1.8.19 и в 2.0.3. Ошибок Java runtaim нет.
Пакет, который я подготовил недавно содержит новый HAL v 0.6.0 и работает только под Windows. Посмотрите в дискуссиях 

UPD: Скорее всего не может прочитать один из файлов Board.txt или Platform.txt
Мне помнится, на какой то версии меняли спецификацию этих файлов. Надо на 
https://github.com/arduino/Arduino/wiki/ смотреть и сравнивать релизы 1,8,13 и 1,8,19
